#!/usr/bin/env bash

# Script to back up in Toshiba HDD ("BackUp")
rsync -aHv --delete --delete-excluded --exclude-from=/home/roy/Documents/Scripts/Backup/exclude_linux.txt --log-file=/home/roy/Documents/Scripts/Backup/Logs/$(date +%Y%m%d)_BackUp_PC_linux.log /home/roy/ /media/roy/BackUp/PCBackup/home/roy

rsync -aHv --delete --delete-excluded --exclude-from=/home/roy/Documents/Scripts/Backup/exclude_win10.txt --log-file=/home/roy/Documents/Scripts/Backup/Logs/$(date +%Y%m%d)_BackUp_PC_win10.log /media/roy/Win10/Users/Roy/ /media/roy/BackUp/PCBackup/Win10/roy

# Script to back up in GreenDrive HDD ("BackUp2")
rsync -aHv --delete --delete-excluded --exclude-from=/home/roy/Documents/Scripts/Backup/exclude_linux.txt --log-file=/home/roy/Documents/Scripts/Backup/Logs/$(date +%Y%m%d)_BackUp2_PC_linux.log /home/roy/ /media/roy/BackUp2/PCBackup/home/roy

rsync -aHv --delete --delete-excluded --exclude-from=/home/roy/Documents/Scripts/Backup/exclude_win10.txt --log-file=/home/roy/Documents/Scripts/Backup/Logs/$(date +%Y%m%d)_BackUp2_PC_win10.log /media/roy/Win10/Users/Roy/ /media/roy/BackUp2/PCBackup/Win10/roy

