#!/usr/bin/env bash

repofile="/home/roy/Documents/Scripts/Git/Repo_list.txt"    # read repos from list
echo "========================================================================"
for repo in $(cat $repofile)    # recursively update local+remote repos
do
    cd $repo
    
    reponame=$(basename `git rev-parse --show-toplevel`)

    echo "CHECKING \"github.com/$reponame\" AGAINST \"$PWD\" ===>"
    echo ""

    git fetch origin

    if git diff --exit-code origin master; then
        diff=false
    else
        diff=true
    fi
    if $diff; then
        git diff --stat origin master
    else
        echo "Remote and local repos are same."
    fi

    echo "========================================================================"
done
