#!/usr/bin/env bash

# 1. Search for text in files using Ripgrep
# 2. Interactively narrow down the list using fzf
# 3. Open the file in Xed/Vim
# (From https://sourcegraph.com/github.com/junegunn/fzf/-/blob/ADVANCED.md#ripgrep-integration)
IFS=: read -ra selected < <(
  rg --color=always \
     --column \
     --line-number \
     --no-heading \
     --hidden \
     --smart-case \
     --glob "!{.cache,.git,.local,.mozilla,.pyenv,.steam}" "${*:-}" |
    fzf --ansi \
        --color "hl:-1:underline,hl+:-1:underline:reverse" \
        --delimiter ":" \
        --preview "head -$LINES {1}" \
        --preview-window "right:50%" \
        --bind "ctrl-/:toggle-preview"
)
[ -n "${selected[0]}" ] && xed "${selected[0]}" "+${selected[1]}"
#[ -n "${selected[0]}" ] && vi "${selected[0]}" "+${selected[1]}"
